### ISSUE TITLE
Incorrect values for input sources for Odyssey G9 OLED

### ISSUE THREAD

**Issue by dlpullen** [TeaRex-coder/hardwareddc#2]
Currently, the code limits the "valid" input source values to 4 values in the handleSetSource function in http.cpp.

These values are:
- 0x0f
- 0x10
- 0x11
- 0x12

The Odyssey G9 OLED is apparently a little different. It only has 3 inputs and the values are:
- 0x05 (Full-size HDMI aka HDMI 1)
- 0x06 (Mini HDMI aka HDMI 2)
- 0x0f (Display Port)

I would propose to either remove the check in line 108 in http.cpp or to add these values to the checked items. I am unsure how much variety there is across different monitors that might benefit from hardwareddc.

As a quick point of comparison, I have some Dell 2721QS monitors with fantastic ddc support. So, no need for hardwareddc for them. But, There input values are:
- 0x0f (Display Port)
- 0x11 (HDMI 1)
- 0x12 (HDMI 2)

These are in better alignment (a subset) with the values you already have setup in the if statement.

**Comment by TeaRex-coder** [comment]
Thanks for opening your issue! I've re-written the API endpoints and removed the check in `http.cpp`.

To switch to HDMI 1 you can now send a request to `http://ddcutil.local:3485/1/input_source/0x05`, more info in the [documentation](/TeaRex-coder/hardwareddc/tree/main/ui).

I'll merge the `api-v2` branch with a PR and close this issue.
